# -*- coding: utf-8 -*-
"""ppt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LC4Iq9oM_2Vw4aQEbyvUAsUSmqhAxiA9
"""

import random
mao = int (input(print('digite (1) para pedra, (2) para papel, (3) para tesoura')))
print(mao)
mylist = [1, 2, 3]
npc = random.choice(mylist)
print(npc)
if mao==npc:
  print('draw')
elif mao==1 and npc==3:
  print('mao wins')
elif mao==2 and npc==1:
  print('mao wins')
elif mao==3 and npc==2:
  print("mao wins")
elif mao==3 and npc==1:
  print('npc wins')
elif mao==1 and npc==2:
  print('npc wins')
elif mao==2 and npc==3:
  print("npc wins")